baseURL = 'https://ericwisnewski.com'
languageCode = 'en-us'
title = 'Eric Wisnewski'
theme = ''

[imaging]
  quality = 85
  resampleFilter = "Lanczos"
  hint = "picture"

[params]
  description = 'Eric Wisnewski â€” personal site and blog'
  nav_school_sheets = '/school-sheets/'
  nav_map = '/map/'
